services:
  db:
    image: postgres:13
    container_name: demo-postgres
    environment:
      POSTGRES_DB: demoapp
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: